### ISSUE TITLE
这个zip无法解压，win 和 mac 都不行

### ISSUE THREAD

**Issue by tangdada** [weui/weui-design#8]
这个zip无法解压，win 和 mac 都不行

**Comment by oh--no** [comment]
发生了什么…发自网易邮箱大师
            在2016年12月29日 11:24，tangdada 写道:这个zip无法解压，win 和 mac 都不行

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/weui/weui-design","title":"weui/weui-design","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/weui/weui-design"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"这个zip无法解压，win 和 mac 都不行 (#8)"}],"action":{"name":"View Issue","url":"https://github.com/weui/weui-design/issues/8"}}}

**Comment by progrape** [comment]
@tangdada 请问是 github 的下载链接 weui-design-master.zip 包 还是指里面的 android-font.zip 包？

**Comment by progrape** [comment]
@tangdada 我们用 http://www.7-zip.org/ 软件可以正常解压
